#define VIAL_KEYBOARD_UID {0xE3, 0x45, 0x8B, 0xB7, 0x40, 0x9E, 0x2E, 0xBC}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_TAP_DANCE_ENTRIES 0
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
