#define VIAL_KEYBOARD_UID {0xCD, 0xA8, 0x39, 0xF1, 0xEF, 0xDE, 0xEB, 0x31}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4

#define LED_PIN_ON_STATE 1
#define LED_NUM_LOCK_PIN GP28
#define LED_CAPS_LOCK_PIN GP1
#define LED_SCROLL_LOCK_PIN GP0
