BOOTMAGIC_ENABLE = yes
COMMAND_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
UNICODE_ENABLE = yes
KEY_LOCK_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes

AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
CONSOLE_ENABLE = no
FAUXCLICKY_ENABLE = no
HD44780_ENABLE = no
MIDI_ENABLE = no
RGBLIGHT_ENABLE = no
SLEEP_LED_ENABLE = no
