#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS]= { 
  /* 0: defuault */
    [0] = LAYOUT(
	KC_PMNS, KC_PAST, KC_PSLS, KC_NUM,  KC_ESC,  KC_1,    KC_2,    KC_3,   KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,  KC_EQL,   KC_BSLS,  KC_BSPC, KC_F1, KC_F2,	  
	KC_PPLS, KC_P9,   KC_P8,   KC_P7,   KC_TAB,  KC_Q,    KC_W,    KC_E,   KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC,  KC_RBRC,  KC_BSLS,  KC_F3,   KC_F4,	
	XXXXXXX, KC_P6,   KC_P5,   KC_P4,   KC_CAPS, KC_A,    KC_S,    KC_D,   KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,            KC_ENT,   KC_F5,   KC_F6,	  
	KC_PENT, KC_P3,   KC_P2,   KC_P1,   KC_LSFT, KC_BSLS, KC_Z,    KC_X,   KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,  KC_RSFT,  XXXXXXX,  KC_F7,   KC_F8,
	XXXXXXX, KC_PDOT, KC_P0,   XXXXXXX, KC_LCTL, KC_LGUI, KC_LALT, KC_SPC,                                              KC_RALT, MO(1),   KC_RGUI,  KC_RCTL,            KC_F9,   KC_F10
	),
      //  ESC             F1       F2       F3       F4       F5       F6       F7      F8        F9       F10       F11     F12       PSCR   SLCK
    [1] = LAYOUT(
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,   KC_GRV,  KC_F1,   KC_F2,   KC_F3,  KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,     KC_F9,   KC_F10,  KC_F11,  KC_F12,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,   XXXXXXX, KC_MSEL, KC_VOLD, KC_VOLU,KC_MUTE, KC_MSTP, KC_MPRV, KC_MPLY, KC_MNXT,   KC_MAIL, KC_WHOM, KC_CALC, KC_WSCH, XXXXXXX, XXXXXXX, XXXXXXX, 
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,   XXXXXXX, AU_ON,   AU_OFF,  CK_UP,  CK_DOWN, CK_RST,  XXXXXXX, XXXXXXX, XXXXXXX,   XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX, XXXXXXX, XXXXXXX,  
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,	 XXXXXXX, XXXXXXX, HF_ON,   HF_OFF, HF_FDBK, HF_RST,  XXXXXXX, XXXXXXX, MKC_MACOS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,	 XXXXXXX, MKC_LG,  XXXXXXX, XXXXXXX,                                               XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX, XXXXXXX 
  ),
    [2] = LAYOUT(
	KC_PMNS, KC_PAST, KC_PSLS, KC_NUM,	  KC_ESC,  KC_1,     KC_2,      KC_3,   KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,      KC_0,     KC_MINS,  KC_EQL,   KC_BSLS,  KC_BSPC, KC_F1, KC_F2,
	KC_PPLS, KC_P9,   KC_P8,   KC_P7,	  KC_TAB,  KC_Q,     KC_W,      KC_E,   KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,      KC_P,     KC_LBRC,  KC_RBRC,  KC_BSLS,  KC_F3,   KC_F4,
	XXXXXXX, KC_P6,   KC_P5,   KC_P4,	  KC_CAPS, KC_A,     KC_S,      KC_D,   KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,      KC_SCLN,  KC_QUOT,            KC_ENT,   KC_F5,   KC_F6,  
	KC_PENT, KC_P3,   KC_P2,   KC_P1,	  KC_LSFT, KC_BSLS,  KC_Z,      KC_X,   KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM,   KC_DOT,   KC_SLSH,  KC_RSFT,  XXXXXXX,  KC_F7,   KC_F8,
	XXXXXXX, KC_PDOT, KC_P0,   XXXXXXX,	  KC_LCTL, MKC_LOPT, MKC_LCOMM, KC_SPC,                                              MKC_RCOMM, MO(3),    MKC_ROPT, KC_RCTL,            KC_F9,   KC_F10
  ),
    [3] = LAYOUT(
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,	KC_GRV,  KC_MSEL, KC_VOLD, KC_VOLU,KC_MUTE, KC_MSTP, KC_MPRV, KC_MPLY, KC_MNXT,   KC_MAIL, KC_WHOM, KC_CALC, KC_WSCH, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,	XXXXXXX, KC_F1,   KC_F2,   KC_F3,  KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,     KC_F9,   KC_F10,  KC_F11,  KC_F12,  XXXXXXX, XXXXXXX, XXXXXXX,
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,  XXXXXXX, AU_ON,   AU_OFF,  CK_UP,  CK_DOWN, CK_RST,  XXXXXXX, XXXXXXX, XXXXXXX,   XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX, XXXXXXX, XXXXXXX,   
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,	XXXXXXX, XXXXXXX, HF_ON,   HF_OFF, HF_FDBK, HF_RST,  XXXXXXX, XXXXXXX, MKC_WIN,   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,	XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                                               XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX, XXXXXXX 
  ),
    [4] = LAYOUT(
    XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,  EE_CLR,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,	XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX, XXXXXXX, XXXXXXX, 
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,	XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
	XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,	XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                                              XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX, XXXXXXX
  )
};

#ifdef AUDIO_ENABLE
  float caps_on[][2] = SONG(CAPS_LOCK_ON_SOUND);
  float caps_off[][2] = SONG(CAPS_LOCK_OFF_SOUND);
  float num_on[][2] = SONG(NUM_LOCK_ON_SOUND);
  float num_off[][2] = SONG(NUM_LOCK_OFF_SOUND);
#endif

bool led_update_user(led_t led_state) {
    #ifdef AUDIO_ENABLE
    static uint8_t caps_state = 0;
    if (caps_state != led_state.caps_lock) {
        led_state.caps_lock ? PLAY_SONG(caps_on) : PLAY_SONG(caps_off);
        caps_state = led_state.caps_lock;
	}
	static uint8_t num_state = 0;
	if (num_state != led_state.num_lock) {
        led_state.num_lock ? PLAY_SONG(num_on) : PLAY_SONG(num_off);
        num_state = led_state.num_lock;
	}
    #endif
    return true;
}
