/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x56, 0x6E, 0x96, 0x2B, 0x01, 0x91, 0x74, 0xB8}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 0
#define VIAL_COMBO_ENTRIES 0
#define VIAL_KEY_OVERRIDE_ENTRIES 0
